# Generated by Django 5.2 on 2025-04-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artwork_artist_alter_artwork_category_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for the artwork.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='artwork',
            field=models.ForeignKey(help_text='The artwork being purchased.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='artworks.artwork'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='pending', help_text='Status of the transaction (e.g., pending, completed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(help_text='Transaction ID from Daraja API.', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(help_text='The user who made the purchase.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
