# Generated by Django 5.2 on 2025-04-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Date of the event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Description of the event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Location of the event.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(help_text='Time of the event (e.g., 10:00 AM - 6:00 PM).', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Title of the event.', max_length=200),
        ),
    ]
