# Generated by Django 5.2 on 2025-04-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_portfolio_alter_artist_social_links_and_more'),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(help_text='The artist who created this artwork.', on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(help_text='Category of the artwork (e.g., graffiti, mural).', max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(help_text='Description of the artwork.'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the artwork.', null=True, upload_to='artworks/images/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the artwork in USD.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text='Title of the artwork.', max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the artwork was uploaded.'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='video',
            field=models.FileField(blank=True, help_text='Video of the artwork (if applicable).', null=True, upload_to='artworks/videos/'),
        ),
    ]
