# Generated by Django 5.2 on 2025-04-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('artists', '0003_alter_artist_portfolio_alter_artist_social_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='artist',
            field=models.ForeignKey(help_text='The artist associated with this analytics entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sales amount for the user/artist.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of the analytics entry.'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='uploads',
            field=models.IntegerField(default=0, help_text='Number of uploads by the user/artist.'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this analytics entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='views',
            field=models.IntegerField(default=0, help_text='Number of views for the user/artist.'),
        ),
    ]
