# Generated by Django 5.2 on 2025-04-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('social_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
