# Generated by Django 5.2 on 2025-04-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='portfolio',
            field=models.TextField(blank=True, help_text="A description of the artist's portfolio."),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Social media links stored as JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='specialty',
            field=models.CharField(blank=True, help_text="The artist's specialty (e.g., graffiti, murals).", max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this artist profile.', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
